title: Elixir Conf EU 2020
description: > # this means to ignore newlines until "baseurl:"
  Elixir conf 2020
baseurl: "/elixirconf-eu-jekyll" # the subpath of your site, e.g. /blog
url: "https://esl.github.io/elixirconf-eu-jekyll" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "./assets/images/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: []

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty

collections:
  speakers:
    output: true
    sort_by: relevance
  trainers:
    output: true
    sort_by: relevance
  trainings:
    output: true
  talks:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "speakers"
    values:
      layout: "speaker"
  - scope:
      path: ""
      type: "trainers"
    values:
      layout: "speaker"
  - scope:
      path: ""
      type: "trainings"
    values:
      layout: "training"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Hilton Warsaw Hotel and Convention Centre
map-text-location: Grzybowska 63, 00-844 Warszawa, Poland
map-lat: 52.2335221
map-lng: 20.9836819

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME




