homepage_settings:
  countdown:
    show: false
    timezone: Europe/Malaga
    deadline: 2025-01-28 11:59
  modal:
    show: false
    delay: 5000
  testimonials:
    show: true
    title: "Testimonials"
  gallery:
    show: true
    title: "ELIXIRCONF EU 2025 HIGHLIGHTS"
  tickets: true
