---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/keynote-list.yml
  label: keynote-list
- type: document
  path: _data/speaker-list.yml
  label: speaker-list
- type: document
  path: _data/talks.yml
  label: talks-list
- type: document
  path: _data/training.yml
  label: training-list
- type: directory
  path: _talks
  label: Talks
  create: documents
  match: "**/*"
  templates:
  - talk
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _videos
  label: Videos
  create: all
  match: "**/*"
  templates:
  - video
- type: directory
  path: _trainings
  label: Trainings
  create: all
  match: "**/*"
- type: directory
  path: _participants
  label: Participants
  create: all
  match: "**/*"
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
